In [ ]:
import pandas as pd
df=pd.read_csv('/content/uncleaned_airline_dataset_20_columns.csv')
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.0,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.0,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,NaN,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.0,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.0,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [ ]:
#2.	Display the first 10 rows of the dataset.
df.head(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,19,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,19,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,19,C101

In [ ]:
#3.	Display the last 10 rows of the dataset.
df.tail(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.0,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.0,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,NaN,NON REFUNDABLE,NONE,NaN,NaN,NaN,19,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.0,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.0,NON REFUNDABLE,veg,25,NaN,NaN,19,C104

In [ ]:
#4.	Find the total number of rows and columns in the dataset.
df.shape

(300153, 20)

In [ ]:
#5.	Display the list of all column names
df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
#6.	Display the data types of all columns
df.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
Passenger_Rating    float64
Ticket_Type          object
Meal_Option          object
Baggage_kg           object
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes         Int64
Customer_ID          object
dtype: object

In [ ]:
#7.	Display basic statistical summary of the dataset
df.describe()

,index,duration,days_left,price,Passenger_Rating,Delay_Minutes
count,300153.000000,300153.000000,300153.000000,300153.000000,224988.000000,300153.0
mean,150076.000000,12.221021,26.004751,20889.660523,3.172458,19.748871
std,86646.852011,7.191997,13.561004,22697.767366,1.342857,17.504764
min,0.000000,0.830000,1.000000,1105.000000,1.000000,0.0
25%,75038.000000,6.830000,15.000000,4783.000000,2.000000,10.0
50%,150076.000000,11.250000,26.000000,7425.000000,4.000000,19.0
75%,225114.000000,16.170000,38.000000,42521.000000,4.000000,19.0
max,300152.000000,49.830000,49.000000,123071.000000,5.000000,60.0

In [ ]:
#8.	Identify which columns contain missing values
df.isnull()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
300149,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300150,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False
300151,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
300152,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False

In [ ]:
#9.	Count the number of missing values in each column.
df.isnull().sum()

index                   0
airline                 0
flight                  0
source_city             0
departure_time          0
stops                   0
arrival_time            0
destination_city        0
class                   0
duration                0
days_left               0
price                   0
Passenger_Rating    75165
Ticket_Type         60296
Meal_Option         59825
Baggage_kg          49689
Checkin_Status      59611
Airport_Terminal    49931
Delay_Minutes           0
Customer_ID         49627
dtype: int64

In [ ]:
#10.	Display the number of unique values in each column.
df.nunique()

index               300153
airline                  6
flight                1561
source_city              6
departure_time           6
stops                    3
arrival_time             6
destination_city         6
class                    2
duration               476
days_left               49
price                12157
Passenger_Rating         5
Ticket_Type              4
Meal_Option              4
Baggage_kg               5
Checkin_Status           4
Airport_Terminal         5
Delay_Minutes            7
Customer_ID              5
dtype: int64

In [ ]:
#11.	Replace missing values in Passenger_Rating with the mean value
df['Passenger_Rating'].fillna(df['Passenger_Rating'].mean(),inplace=True)

/tmp/ipykernel_608/2131421203.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Passenger_Rating'].fillna(df['Passenger_Rating'].mean(),inplace=True)

In [ ]:
#12.	Replace missing values in Meal_Option with "Unknown
df['Meal_Option'].fillna('Unknown',inplace=True)

/tmp/ipykernel_608/1611900147.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Meal_Option'].fillna('Unknown',inplace=True)

In [ ]:
#13.	Replace missing values in Baggage_kg with the median value
df['Baggage_kg'] = df['Baggage_kg'].str.replace('kg', '', regex=False)
df['Baggage_kg'] = pd.to_numeric(df['Baggage_kg'], errors='coerce')
df['Baggage_kg'].fillna(df['Baggage_kg'].median(),inplace=True)

/tmp/ipykernel_608/2113528868.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Baggage_kg'].fillna(df['Baggage_kg'].median(),inplace=True)

In [ ]:
df['Baggage_kg'].isnull().sum()

np.int64(0)

In [ ]:
#14.	Remove rows where Customer_ID is missing.
df.dropna(subset=['Customer_ID'],inplace=True)

In [ ]:
#15.	Verify that missing values are handled
df.isnull().sum()

index                   0
airline                 0
flight                  0
source_city             0
departure_time          0
stops                   0
arrival_time            0
destination_city        0
class                   0
duration                0
days_left               0
price                   0
Passenger_Rating        0
Ticket_Type         50326
Meal_Option             0
Baggage_kg              0
Checkin_Status      49723
Airport_Terminal    41677
Delay_Minutes           0
Customer_ID             0
dtype: int64

In [ ]:
#16.	Remove leading and trailing spaces from all string columns
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [ ]:
#17.	Convert Meal_Option values to lowercase
df['Meal_Option'] = df['Meal_Option'].str.lower()

In [ ]:
#18.	Convert Ticket_Type values to proper format (Refundable / Non-Refundable).
df['Ticket_Type'] = df['Ticket_Type'].str.strip().str.title()

In [ ]:
#19.	Standardize Checkin_Status values
df['Checkin_Status'] = df['Checkin_Status'].str.strip().str.title()

In [ ]:
#20.	Standardize Airport_Terminal values to T1, T2, T3 format
df['Airport_Terminal'] = df['Airport_Terminal'].str.lower().str.strip()
df['Airport_Terminal'] = df['Airport_Terminal'].replace({
    'terminal-1':'T1',
    'terminal-2':'T2',
    'terminal-3':'T3'
})
df['Airport_Terminal'] = df['Airport_Terminal'].str.upper().str.strip()

In [ ]:
#21.	Convert Passenger_Rating column to numeric datatype.
df['Passenger_Rating']=df['Passenger_Rating'].astype(int)

In [ ]:
#23.	Convert Delay_Minutes column into integer datatype.
df['Delay_Minutes'] = pd.to_numeric(df['Delay_Minutes'], errors='coerce').astype('Int64')

In [ ]:
df['Delay_Minutes'] = df['Delay_Minutes'].fillna(0)

In [ ]:
#24.	Replace "unknown" values with NaN.
import numpy as np

df['Delay_Minutes'] = df['Delay_Minutes'].replace(0, np.nan)

In [ ]:
#25.	Verify the updated data types
df.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
Passenger_Rating      int64
Ticket_Type          object
Meal_Option          object
Baggage_kg          float64
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes         Int64
Customer_ID          object
dtype: object

In [ ]:
#26.	Check whether duplicate rows exist in the dataset.
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
300148    False
300149    False
300150    False
300151    False
300152    False
Length: 250526, dtype: bool

In [ ]:
#27.	Count the number of duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
#28.	Remove duplicate rows from the dataset.
df.drop_duplicates(inplace=True)

In [ ]:
#29.	Find the total number of flights in the dataset.
df['flight'].count()

np.int64(250526)

In [ ]:
#30.	Find the number of unique airlines
df['airline'].nunique()

6

In [ ]:
#31.	Display the list of unique source cities.
df['source_city'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [ ]:
#32.	Display the list of unique destination cities.
df['destination_city'].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [ ]:
#33.	Count flights for each airline.
df['airline'].value_counts()

airline
Vistara      106656
Air_India     67465
Indigo        36105
GO_FIRST      19368
AirAsia       13402
SpiceJet       7530
Name: count, dtype: int64

In [ ]:
#34.	Find the average ticket price.
df['price'].mean()

np.float64(20859.455409817743)

In [ ]:
#35.	Find the maximum ticket price.
df['price'].max()

123071

In [ ]:
#36.	Find the minimum ticket price
df['price'].min()

1105

In [ ]:
#37.	Find the average ticket price for each airline.
df.groupby('airline')['price'].mean()

airline
AirAsia       4090.437397
Air_India    23462.339613
GO_FIRST      5650.079667
Indigo        5324.947320
SpiceJet      6180.799203
Vistara      30377.097941
Name: price, dtype: float64

In [ ]:
#38.	Display the top 5 most expensive flights
df.nlargest(5,'price')
#df.sort_values(by='price', ascending=False).head(5)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
261377,261377,Vistara,UK-772,Kolkata,Morning,one,Night,Delhi,Business,13.50,3,123071,3,NaN,none,20.0,NaN,T2,19,C104
216096,216096,Vistara,UK-811,Delhi,Early_Morning,two_or_more,Evening,Kolkata,Business,10.92,5,117307,5,Non-Refundable,non-veg,30.0,Checked-In,T2,10,C104
215859,215859,Vistara,UK-809,Delhi,Evening,two_or_more,Evening,Kolkata,Business,21.08,1,116562,4,Refundable,unknown,30.0,Not Checked,T1,15,C103
277345,277345,Vistara,UK-870,Hyderabad,Night,one,Afternoon,Mumbai,Business,16.42,3,115211,5,NaN,unknown,30.0,NaN,T2,19,C102
270999,270999,Vistara,UK-772,Kolkata,Morning,one,Evening,Hyderabad,Business,9.50,17,114705,4,NaN,none,20.0,Not Checked,T3,10,C104

In [ ]:
#39.	Find the number of flights from each source city.
df['source_city'].value_counts()
#df.groupby('source_city')['flight'].count()

source_city
Delhi        51252
Mumbai       50793
Bangalore    43400
Kolkata      38765
Hyderabad    33995
Chennai      32321
Name: count, dtype: int64

In [ ]:
#40.	Find the number of flights to each destination city
df['destination_city'].value_counts()
#df.groupby('destination_city')['flight'].count

destination_city
Mumbai       49207
Delhi        47760
Bangalore    42789
Kolkata      41396
Hyderabad    35641
Chennai      33733
Name: count, dtype: int64

In [ ]:
#41.	Identify the source city with the most flights
df['source_city'].mode()

0    Delhi
Name: source_city, dtype: object

In [ ]:
#42.	Find the average ticket price for each source city.
df.groupby('source_city')['price'].mean()

source_city
Bangalore    21357.327535
Chennai      21931.586956
Delhi        18930.201904
Hyderabad    20208.695749
Kolkata      21785.402528
Mumbai       21427.374638
Name: price, dtype: float64

In [ ]:
#43.	Count flights based on number of stops.
df['stops'].value_counts()

stops
one            209269
zero            30164
two_or_more     11093
Name: count, dtype: int64

In [ ]:
#44.	Find the average price based on flight class
df.groupby('class')['price'].mean()

class
Business    52533.982832
Economy      6571.986777
Name: price, dtype: float64

In [ ]:
#45.	Find the airline with the highest average passenger rating.
df.groupby('airline')['Passenger_Rating'].mean().idxmax()

'GO_FIRST'

In [ ]:
#46.	Count flights based on departure time.
df['departure_time'].value_counts()
#df.groupby('departure_time')['flight'].count()

departure_time
Morning          59473
Early_Morning    55837
Evening          54425
Night            39880
Afternoon        39820
Late_Night        1091
Name: count, dtype: int64

np.int64(31297)

In [ ]:
df['Delay_Minutes'] = pd.to_numeric(df['Delay_Minutes'], errors='coerce').astype('Int64')
df['Delay_Minutes'] = df['Delay_Minutes'].fillna(int(df['Delay_Minutes'].mean()))

In [ ]:
#47.	Find the average delay minutes of flights
df['Delay_Minutes'].mean()

np.float64(22.48935040674421)

In [ ]:
#48.	Display flights delayed more than 30 minutes.
df[df['Delay_Minutes']>30]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
12,12,Indigo,6E-5001,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955,5,Non Refundable,non-veg,20.0,NaN,T2,60,C101
28,28,SpiceJet,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260,3,Non-Refundable,non-veg,30.0,Checked,T3,60,C105
33,33,Vistara,UK-817,Delhi,Evening,one,Morning,Mumbai,Economy,16.17,1,12150,1,Non-Refundable,veg,15.0,NaN,T2,60,C103
34,34,Vistara,UK-819,Delhi,Afternoon,one,Morning,Mumbai,Economy,18.00,1,12150,4,Refundable,veg,30.0,Checked,NaN,60,C102
37,37,Air_India,AI-453,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,8.83,1,11900,4,NaN,veg,15.0,Checked-In,T1,60,C105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300100,300100,Vistara,UK-838,Chennai,Night,one,Morning,Hyderabad,Business,12.33,48,58032,1,Refundable,non-veg,25.0,Checked,T1,60,C101
300106,300106,Vistara,UK-834,Chennai,Evening,one,Evening,Hyderabad,Business,23.58,48,80544,2,Non-Refundable,non-veg,20.0,Checked-In,T2,60,C104
300136,300136,Vistara,UK-834,Chennai,Evening,one,Evening,Hyderabad,Business,23.58,49,51457,3,Non Refundable,veg,15.0,Checked-In,T1,60,C104
300142,300142,Air_India,AI-539,Chennai,Evening,one,Morning,Hyderabad,Business,16.00,49,51345,4,Refundable,non-veg,25.0,Checked,NaN,60,C102
300145,300145,Air_India,AI-430,Chennai,Morning,one,Morning,Hyderabad,Business,23.08,49,51345,4,Non Refundable,veg,20.0,Checked-In,TERMINAL 1,60,C105

In [ ]:
#49.	Save the cleaned dataset as clean_airline_dataset.csv.
df.isnull().sum()

index                   0
airline                 0
flight                  0
source_city             0
departure_time          0
stops                   0
arrival_time            0
destination_city        0
class                   0
duration                0
days_left               0
price                   0
Passenger_Rating        0
Ticket_Type             0
Meal_Option             0
Baggage_kg              0
Checkin_Status          0
Airport_Terminal    41677
Delay_Minutes           0
Customer_ID             0
dtype: int64

In [ ]:
df['Ticket_Type'].fillna('Unknown',inplace=True)
df['Checkin_Status'].fillna('Unknown',inplace=True)
df['Airport_Terminal'].fillna('Unknown',inplace=True)

/tmp/ipykernel_608/2970080321.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Airport_Terminal'].fillna('Unknown',inplace=True)

In [ ]:
df.isnull().sum()

index               0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
Passenger_Rating    0
Ticket_Type         0
Meal_Option         0
Baggage_kg          0
Checkin_Status      0
Airport_Terminal    0
Delay_Minutes       0
Customer_ID         0
dtype: int64

In [ ]:
#49.	Save the cleaned dataset as clean_airline_dataset.csv.
df.to_csv("cleaned_airline_dataset.csv", index=False)

In [ ]:
#50.	Display the final shape of the cleaned dataset.
df.shape

(250526, 20)